cordinate_attack_task:
  description: >
    Léia deve coordenar a missão,
    mantendo a comunicação e fornecendo suporte estratégico.
    Léia deve ordenar primeiro que Han defenda o Luke,
    possibilitando um caminho seguro para ele.
  expected_output: >
    Ataque coordenado com sucesso,
    estrela da morte destruída.
    Todas as unidade informada e alinhadas.

protect_luke_task:
  description: >
    Han deve atacar naves inimigas e proteger Luke de ser atacado durante a missão.
  expected_output: >
    Luke protegido, caminho livre para o ataque final.

destroy_dead_star_task:
  description: >
    Luke deve pilotar sua X-wing e atirar no pronto fraco da Estrela da Morte para destruíla.
  expected_output: >
    Estrela da Morte destruída, missão bem-sucedida.

